OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Manufacturer 
    Domain: manufacturer.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
